version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  node-6.0:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  node-12.4:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  codecov:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test-coverage
      - run: npm run codecov

workflows:
  version: 2
  build:
    jobs:
      - lint
<<<<<<< HEAD
      - test
=======
      - node-6.0
      - node-12.4
      - codecov
>>>>>>> bffb0d3e3f0b177e5cd0d2678f49ec3e09bebf88
