version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  node-12.4:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: pm2 start index.js
      - run: npm run test
      - run: pm2 stop 0

  codecov:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: pm2 start index.js
      - run: npm run test-coverage
      - run: npm run codecov
      - run: pm2 stop 0

workflows:
  version: 2
  build:
    jobs:
      - lint
      - node-12.4
      - codecov